ALTER TABLE visitors ADD COLUMN IF NOT EXISTS is_proxy BOOLEAN DEFAULT false;
ALTER TABLE visitors ADD COLUMN IF NOT EXISTS is_tor BOOLEAN DEFAULT false;
ALTER TABLE visitors ADD COLUMN IF NOT EXISTS is_temp_email BOOLEAN DEFAULT false;
